### ISSUE TITLE
Update checklist for 1.1.1

### ISSUE THREAD

**Issue by TheProtagonists** [TheProtagonists/TheWorldBeyond#1]
1.1.1 Checklist

- [x] Further tweaks (reduction) on asteroid spawn rate
- [x] Fix version file and add actual and correct version checking
- [x] License descriptions for sunflares
- [x] Custom orbit icons for stars
- [x] Remake Barrier's pulsar emission jets
- [x] Adjustments to Eon's planets' orbits
- [x] More loading tips and resort current tips
- [x] More flags of planets and moons

----

- [x] Index on CKAN
