### ISSUE TITLE
Update checklist for 1.2

### ISSUE THREAD

**Issue by TheProtagonists** [TheProtagonists/TheWorldBeyond#2]
1.2 Checklist

- [x] 1 new planet for Wall
       - Also move everything on a really inclined orbit and give Nyarlathotep a polar ring
- [ ] 2 new planets for Eon
- [ ] 8 new moons for Newell
       - Adjust Newell's rings accordingly
- [ ] 3 new moons for Sora
       - change the orbit color of Sora's moons
- [ ] 7 new gas giants for Ascension
       - Put Q'uq'umatz and Harmony around two of them
- [ ] Completely remake Zhuque
- [ ] Completely remake Infinity and rrename it to Albion
- [x] Remove Cerberus and Baldr
- [ ] Remove Bahamut and Heimdallr, and add a new planet in Bahamut's place
       - change orbit colors in the Paradise system, and change the flag of the system
- [x] Remake star coronas
- [ ] Remake the first two aurora textures
- [x] Implement a base translation framework
- [ ] Update all scatterer configs
- [ ] Even more flags

----

Other goals
- Nice looking diagrams for each system
- More screenshots and mission patches (?)

Possibilities
- Comet trails using Kopernicus Expansion
- Replace Oblivion's ring with a proper protoplanetary disc using INSTANTIATOR
- Glowing lava oceans for lava planets using Kopernicus Expansion

**Comment by DeltaDizzy** [comment]
Wait Wait Wait.
You're removing Bahamut? What will happen to Asgard?

**Comment by TheProtagonists** [comment]
I'm re-adding (and remaking) Bahamut and Heimdallr to somewhere in Traverse.
~~Asgard will probably take Bahamut's current orbit unless I think of something else.~~

Now that I think about it I might just put another (habitable) planet in it's place...
